server.port=8080

# Enabling the H2-Console (local and remote)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Password for the H2-Console
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/platemate;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

app.auth.cookie.secure=false
server.error.include-message=always